// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entc/integration/edgeschema/ent/parentship"
	"entgo.io/ent/entc/integration/edgeschema/ent/predicate"
	"entgo.io/ent/schema/field"
)

// ParentshipUpdate is the builder for updating Parentship entities.
type ParentshipUpdate struct {
	config
	hooks    []Hook
	mutation *ParentshipMutation
}

// Where appends a list predicates to the ParentshipUpdate builder.
func (_u *ParentshipUpdate) Where(ps ...predicate.Parentship) *ParentshipUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetWeight sets the "weight" field.
func (_u *ParentshipUpdate) SetWeight(v int) *ParentshipUpdate {
	_u.mutation.ResetWeight()
	_u.mutation.SetWeight(v)
	return _u
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_u *ParentshipUpdate) SetNillableWeight(v *int) *ParentshipUpdate {
	if v != nil {
		_u.SetWeight(*v)
	}
	return _u
}

// AddWeight adds value to the "weight" field.
func (_u *ParentshipUpdate) AddWeight(v int) *ParentshipUpdate {
	_u.mutation.AddWeight(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ParentshipUpdate) SetCreatedAt(v time.Time) *ParentshipUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ParentshipUpdate) SetNillableCreatedAt(v *time.Time) *ParentshipUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the ParentshipMutation object of the builder.
func (_u *ParentshipUpdate) Mutation() *ParentshipMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ParentshipUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ParentshipUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ParentshipUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ParentshipUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ParentshipUpdate) check() error {
	if _u.mutation.ParentCleared() && len(_u.mutation.ParentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Parentship.parent"`)
	}
	if _u.mutation.ChildCleared() && len(_u.mutation.ChildIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Parentship.child"`)
	}
	return nil
}

func (_u *ParentshipUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(parentship.Table, parentship.Columns, sqlgraph.NewFieldSpec(parentship.FieldChildID, field.TypeInt), sqlgraph.NewFieldSpec(parentship.FieldParentID, field.TypeInt))
	if ps := _u.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Weight(); ok {
		_spec.SetField(parentship.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWeight(); ok {
		_spec.AddField(parentship.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(parentship.FieldCreatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{parentship.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ParentshipUpdateOne is the builder for updating a single Parentship entity.
type ParentshipUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ParentshipMutation
}

// SetWeight sets the "weight" field.
func (_u *ParentshipUpdateOne) SetWeight(v int) *ParentshipUpdateOne {
	_u.mutation.ResetWeight()
	_u.mutation.SetWeight(v)
	return _u
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_u *ParentshipUpdateOne) SetNillableWeight(v *int) *ParentshipUpdateOne {
	if v != nil {
		_u.SetWeight(*v)
	}
	return _u
}

// AddWeight adds value to the "weight" field.
func (_u *ParentshipUpdateOne) AddWeight(v int) *ParentshipUpdateOne {
	_u.mutation.AddWeight(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ParentshipUpdateOne) SetCreatedAt(v time.Time) *ParentshipUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ParentshipUpdateOne) SetNillableCreatedAt(v *time.Time) *ParentshipUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the ParentshipMutation object of the builder.
func (_u *ParentshipUpdateOne) Mutation() *ParentshipMutation {
	return _u.mutation
}

// Where appends a list predicates to the ParentshipUpdate builder.
func (_u *ParentshipUpdateOne) Where(ps ...predicate.Parentship) *ParentshipUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ParentshipUpdateOne) Select(field string, fields ...string) *ParentshipUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Parentship entity.
func (_u *ParentshipUpdateOne) Save(ctx context.Context) (*Parentship, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ParentshipUpdateOne) SaveX(ctx context.Context) *Parentship {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ParentshipUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ParentshipUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ParentshipUpdateOne) check() error {
	if _u.mutation.ParentCleared() && len(_u.mutation.ParentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Parentship.parent"`)
	}
	if _u.mutation.ChildCleared() && len(_u.mutation.ChildIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Parentship.child"`)
	}
	return nil
}

func (_u *ParentshipUpdateOne) sqlSave(ctx context.Context) (_node *Parentship, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(parentship.Table, parentship.Columns, sqlgraph.NewFieldSpec(parentship.FieldChildID, field.TypeInt), sqlgraph.NewFieldSpec(parentship.FieldParentID, field.TypeInt))
	if id, ok := _u.mutation.ChildID(); !ok {
		return nil, &ValidationError{Name: "child_id", err: errors.New(`ent: missing "Parentship.child_id" for update`)}
	} else {
		_spec.Node.CompositeID[0].Value = id
	}
	if id, ok := _u.mutation.ParentID(); !ok {
		return nil, &ValidationError{Name: "parent_id", err: errors.New(`ent: missing "Parentship.parent_id" for update`)}
	} else {
		_spec.Node.CompositeID[1].Value = id
	}
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, len(fields))
		for i, f := range fields {
			if !parentship.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			_spec.Node.Columns[i] = f
		}
	}
	if ps := _u.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Weight(); ok {
		_spec.SetField(parentship.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWeight(); ok {
		_spec.AddField(parentship.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(parentship.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &Parentship{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{parentship.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
