// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/entc/integration/edgeschema/ent/parentship"
	"entgo.io/ent/entc/integration/edgeschema/ent/user"
)

// Parentship is the model entity for the Parentship schema.
type Parentship struct {
	config `json:"-"`
	// Weight holds the value of the "weight" field.
	Weight int `json:"weight,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// ParentID holds the value of the "parent_id" field.
	ParentID int `json:"parent_id,omitempty"`
	// ChildID holds the value of the "child_id" field.
	ChildID int `json:"child_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ParentshipQuery when eager-loading is set.
	Edges        ParentshipEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ParentshipEdges holds the relations/edges for other nodes in the graph.
type ParentshipEdges struct {
	// Parent holds the value of the parent edge.
	Parent *User `json:"parent,omitempty"`
	// Child holds the value of the child edge.
	Child *User `json:"child,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ParentOrErr returns the Parent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ParentshipEdges) ParentOrErr() (*User, error) {
	if e.Parent != nil {
		return e.Parent, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "parent"}
}

// ChildOrErr returns the Child value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ParentshipEdges) ChildOrErr() (*User, error) {
	if e.Child != nil {
		return e.Child, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "child"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Parentship) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case parentship.FieldWeight, parentship.FieldParentID, parentship.FieldChildID:
			values[i] = new(sql.NullInt64)
		case parentship.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Parentship fields.
func (_m *Parentship) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case parentship.FieldWeight:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field weight", values[i])
			} else if value.Valid {
				_m.Weight = int(value.Int64)
			}
		case parentship.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case parentship.FieldParentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field parent_id", values[i])
			} else if value.Valid {
				_m.ParentID = int(value.Int64)
			}
		case parentship.FieldChildID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field child_id", values[i])
			} else if value.Valid {
				_m.ChildID = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Parentship.
// This includes values selected through modifiers, order, etc.
func (_m *Parentship) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryParent queries the "parent" edge of the Parentship entity.
func (_m *Parentship) QueryParent() *UserQuery {
	return NewParentshipClient(_m.config).QueryParent(_m)
}

// QueryChild queries the "child" edge of the Parentship entity.
func (_m *Parentship) QueryChild() *UserQuery {
	return NewParentshipClient(_m.config).QueryChild(_m)
}

// Update returns a builder for updating this Parentship.
// Note that you need to call Parentship.Unwrap() before calling this method if this Parentship
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Parentship) Update() *ParentshipUpdateOne {
	return NewParentshipClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Parentship entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Parentship) Unwrap() *Parentship {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Parentship is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Parentship) String() string {
	var builder strings.Builder
	builder.WriteString("Parentship(")
	builder.WriteString("weight=")
	builder.WriteString(fmt.Sprintf("%v", _m.Weight))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("parent_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ParentID))
	builder.WriteString(", ")
	builder.WriteString("child_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChildID))
	builder.WriteByte(')')
	return builder.String()
}

// Parentships is a parsable slice of Parentship.
type Parentships []*Parentship
