// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entc/integration/edgeschema/ent/parentship"
	"entgo.io/ent/entc/integration/edgeschema/ent/user"
	"entgo.io/ent/schema/field"
)

// ParentshipCreate is the builder for creating a Parentship entity.
type ParentshipCreate struct {
	config
	mutation *ParentshipMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetWeight sets the "weight" field.
func (_c *ParentshipCreate) SetWeight(v int) *ParentshipCreate {
	_c.mutation.SetWeight(v)
	return _c
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_c *ParentshipCreate) SetNillableWeight(v *int) *ParentshipCreate {
	if v != nil {
		_c.SetWeight(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ParentshipCreate) SetCreatedAt(v time.Time) *ParentshipCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ParentshipCreate) SetNillableCreatedAt(v *time.Time) *ParentshipCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetParentID sets the "parent_id" field.
func (_c *ParentshipCreate) SetParentID(v int) *ParentshipCreate {
	_c.mutation.SetParentID(v)
	return _c
}

// SetChildID sets the "child_id" field.
func (_c *ParentshipCreate) SetChildID(v int) *ParentshipCreate {
	_c.mutation.SetChildID(v)
	return _c
}

// SetParent sets the "parent" edge to the User entity.
func (_c *ParentshipCreate) SetParent(v *User) *ParentshipCreate {
	return _c.SetParentID(v.ID)
}

// SetChild sets the "child" edge to the User entity.
func (_c *ParentshipCreate) SetChild(v *User) *ParentshipCreate {
	return _c.SetChildID(v.ID)
}

// Mutation returns the ParentshipMutation object of the builder.
func (_c *ParentshipCreate) Mutation() *ParentshipMutation {
	return _c.mutation
}

// Save creates the Parentship in the database.
func (_c *ParentshipCreate) Save(ctx context.Context) (*Parentship, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ParentshipCreate) SaveX(ctx context.Context) *Parentship {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ParentshipCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ParentshipCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ParentshipCreate) defaults() error {
	if _, ok := _c.mutation.Weight(); !ok {
		v := parentship.DefaultWeight
		_c.mutation.SetWeight(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if parentship.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized parentship.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := parentship.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *ParentshipCreate) check() error {
	if _, ok := _c.mutation.Weight(); !ok {
		return &ValidationError{Name: "weight", err: errors.New(`ent: missing required field "Parentship.weight"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Parentship.created_at"`)}
	}
	if _, ok := _c.mutation.ParentID(); !ok {
		return &ValidationError{Name: "parent_id", err: errors.New(`ent: missing required field "Parentship.parent_id"`)}
	}
	if _, ok := _c.mutation.ChildID(); !ok {
		return &ValidationError{Name: "child_id", err: errors.New(`ent: missing required field "Parentship.child_id"`)}
	}
	if len(_c.mutation.ParentIDs()) == 0 {
		return &ValidationError{Name: "parent", err: errors.New(`ent: missing required edge "Parentship.parent"`)}
	}
	if len(_c.mutation.ChildIDs()) == 0 {
		return &ValidationError{Name: "child", err: errors.New(`ent: missing required edge "Parentship.child"`)}
	}
	return nil
}

func (_c *ParentshipCreate) sqlSave(ctx context.Context) (*Parentship, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}

func (_c *ParentshipCreate) createSpec() (*Parentship, *sqlgraph.CreateSpec) {
	var (
		_node = &Parentship{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(parentship.Table, nil)
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Weight(); ok {
		_spec.SetField(parentship.FieldWeight, field.TypeInt, value)
		_node.Weight = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(parentship.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   parentship.ParentTable,
			Columns: []string{parentship.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ParentID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChildIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   parentship.ChildTable,
			Columns: []string{parentship.ChildColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ChildID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Parentship.Create().
//		SetWeight(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ParentshipUpsert) {
//			SetWeight(v+v).
//		}).
//		Exec(ctx)
func (_c *ParentshipCreate) OnConflict(opts ...sql.ConflictOption) *ParentshipUpsertOne {
	_c.conflict = opts
	return &ParentshipUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Parentship.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ParentshipCreate) OnConflictColumns(columns ...string) *ParentshipUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ParentshipUpsertOne{
		create: _c,
	}
}

type (
	// ParentshipUpsertOne is the builder for "upsert"-ing
	//  one Parentship node.
	ParentshipUpsertOne struct {
		create *ParentshipCreate
	}

	// ParentshipUpsert is the "OnConflict" setter.
	ParentshipUpsert struct {
		*sql.UpdateSet
	}
)

// SetWeight sets the "weight" field.
func (u *ParentshipUpsert) SetWeight(v int) *ParentshipUpsert {
	u.Set(parentship.FieldWeight, v)
	return u
}

// UpdateWeight sets the "weight" field to the value that was provided on create.
func (u *ParentshipUpsert) UpdateWeight() *ParentshipUpsert {
	u.SetExcluded(parentship.FieldWeight)
	return u
}

// AddWeight adds v to the "weight" field.
func (u *ParentshipUpsert) AddWeight(v int) *ParentshipUpsert {
	u.Add(parentship.FieldWeight, v)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *ParentshipUpsert) SetCreatedAt(v time.Time) *ParentshipUpsert {
	u.Set(parentship.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ParentshipUpsert) UpdateCreatedAt() *ParentshipUpsert {
	u.SetExcluded(parentship.FieldCreatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Parentship.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ParentshipUpsertOne) UpdateNewValues() *ParentshipUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ParentID(); exists {
			s.SetIgnore(parentship.FieldParentID)
		}
		if _, exists := u.create.mutation.ChildID(); exists {
			s.SetIgnore(parentship.FieldChildID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Parentship.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ParentshipUpsertOne) Ignore() *ParentshipUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ParentshipUpsertOne) DoNothing() *ParentshipUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ParentshipCreate.OnConflict
// documentation for more info.
func (u *ParentshipUpsertOne) Update(set func(*ParentshipUpsert)) *ParentshipUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ParentshipUpsert{UpdateSet: update})
	}))
	return u
}

// SetWeight sets the "weight" field.
func (u *ParentshipUpsertOne) SetWeight(v int) *ParentshipUpsertOne {
	return u.Update(func(s *ParentshipUpsert) {
		s.SetWeight(v)
	})
}

// AddWeight adds v to the "weight" field.
func (u *ParentshipUpsertOne) AddWeight(v int) *ParentshipUpsertOne {
	return u.Update(func(s *ParentshipUpsert) {
		s.AddWeight(v)
	})
}

// UpdateWeight sets the "weight" field to the value that was provided on create.
func (u *ParentshipUpsertOne) UpdateWeight() *ParentshipUpsertOne {
	return u.Update(func(s *ParentshipUpsert) {
		s.UpdateWeight()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *ParentshipUpsertOne) SetCreatedAt(v time.Time) *ParentshipUpsertOne {
	return u.Update(func(s *ParentshipUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ParentshipUpsertOne) UpdateCreatedAt() *ParentshipUpsertOne {
	return u.Update(func(s *ParentshipUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *ParentshipUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ParentshipCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ParentshipUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// ParentshipCreateBulk is the builder for creating many Parentship entities in bulk.
type ParentshipCreateBulk struct {
	config
	err      error
	builders []*ParentshipCreate
	conflict []sql.ConflictOption
}

// Save creates the Parentship entities in the database.
func (_c *ParentshipCreateBulk) Save(ctx context.Context) ([]*Parentship, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Parentship, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ParentshipMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ParentshipCreateBulk) SaveX(ctx context.Context) []*Parentship {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ParentshipCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ParentshipCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Parentship.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ParentshipUpsert) {
//			SetWeight(v+v).
//		}).
//		Exec(ctx)
func (_c *ParentshipCreateBulk) OnConflict(opts ...sql.ConflictOption) *ParentshipUpsertBulk {
	_c.conflict = opts
	return &ParentshipUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Parentship.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ParentshipCreateBulk) OnConflictColumns(columns ...string) *ParentshipUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ParentshipUpsertBulk{
		create: _c,
	}
}

// ParentshipUpsertBulk is the builder for "upsert"-ing
// a bulk of Parentship nodes.
type ParentshipUpsertBulk struct {
	create *ParentshipCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Parentship.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ParentshipUpsertBulk) UpdateNewValues() *ParentshipUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ParentID(); exists {
				s.SetIgnore(parentship.FieldParentID)
			}
			if _, exists := b.mutation.ChildID(); exists {
				s.SetIgnore(parentship.FieldChildID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Parentship.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ParentshipUpsertBulk) Ignore() *ParentshipUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ParentshipUpsertBulk) DoNothing() *ParentshipUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ParentshipCreateBulk.OnConflict
// documentation for more info.
func (u *ParentshipUpsertBulk) Update(set func(*ParentshipUpsert)) *ParentshipUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ParentshipUpsert{UpdateSet: update})
	}))
	return u
}

// SetWeight sets the "weight" field.
func (u *ParentshipUpsertBulk) SetWeight(v int) *ParentshipUpsertBulk {
	return u.Update(func(s *ParentshipUpsert) {
		s.SetWeight(v)
	})
}

// AddWeight adds v to the "weight" field.
func (u *ParentshipUpsertBulk) AddWeight(v int) *ParentshipUpsertBulk {
	return u.Update(func(s *ParentshipUpsert) {
		s.AddWeight(v)
	})
}

// UpdateWeight sets the "weight" field to the value that was provided on create.
func (u *ParentshipUpsertBulk) UpdateWeight() *ParentshipUpsertBulk {
	return u.Update(func(s *ParentshipUpsert) {
		s.UpdateWeight()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *ParentshipUpsertBulk) SetCreatedAt(v time.Time) *ParentshipUpsertBulk {
	return u.Update(func(s *ParentshipUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ParentshipUpsertBulk) UpdateCreatedAt() *ParentshipUpsertBulk {
	return u.Update(func(s *ParentshipUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *ParentshipUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ParentshipCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ParentshipCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ParentshipUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
